# Generated by Django 5.2.7 on 2025-12-11 20:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Serviço')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18, verbose_name='CNPJ')),
                ('razao_social', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('filial', models.CharField(choices=[('MATRIZ_SP', 'BIRDAY MATRIZ E FILIAL SP'), ('FILIAL_PB', 'FILIAL PB'), ('FILIAL_GO', 'FILIAL GO')], default='MATRIZ_SP', max_length=20, verbose_name='Filial Transbirday')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('nome_contato', models.CharField(max_length=100, verbose_name='Nome do Contato')),
                ('telefone_contato', models.CharField(max_length=20, verbose_name='Telefone do Contato')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('cadastrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_cadastrados', to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado Por')),
            ],
        ),
        migrations.CreateModel(
            name='ClienteProspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ')),
                ('razao_social', models.CharField(max_length=255, verbose_name='Razão Social / Nome')),
                ('nome_contato', models.CharField(max_length=100, verbose_name='Nome do Contato')),
                ('telefone_contato', models.CharField(max_length=20, verbose_name='Telefone do Contato')),
                ('email_contato', models.EmailField(blank=True, max_length=100, null=True, verbose_name='E-mail')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('cadastrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prospects_cadastrados', to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado Por')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('eh_representante', models.BooleanField(default=False, verbose_name='É Representante Comercial?')),
                ('setor', models.CharField(choices=[('REPRESENTANTE', 'Representante Comercial'), ('FINANCEIRO', 'Financeiro'), ('COMERCIAL', 'Diretoria Comercial'), ('ADMIN', 'Administrativo')], default='REPRESENTANTE', max_length=20, verbose_name='Setor / Função')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prospeccao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOVA', 'Nova'), ('NEGOCIANDO', 'Em Negociação'), ('FECHADO', 'Serviço Fechado'), ('DESISTENCIA', 'Desistência do Cliente'), ('PERDIDA', 'Negociação Perdida')], default='NOVA', max_length=20)),
                ('tipo_proposta', models.CharField(choices=[('FRACIONADO', 'Fracionado'), ('DEDICADO', 'Dedicado'), ('ARMAZENAGEM', 'Armazenagem')], max_length=20, verbose_name='Tipo de Proposta')),
                ('duracao_meses', models.PositiveIntegerField(verbose_name='Duração em Meses (Aprox.)')),
                ('viagens_aproximadas', models.PositiveIntegerField(verbose_name='Nº de Viagens (Aprox.)')),
                ('valor_medio_viagem', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Médio por Viagem')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total Estimado')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_inicio_negociacao', models.DateTimeField(blank=True, null=True)),
                ('data_finalizacao', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospeccoes', to='app.clienteprospect')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prospeccoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('finalizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prospeccoes_finalizadas', to=settings.AUTH_USER_MODEL)),
                ('iniciado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prospeccoes_iniciadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AcaoProspeccao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição da Ação')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='uploads/prospeccao/%Y/%m/', verbose_name='Arquivo Anexo')),
                ('data_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('prospeccao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes', to='app.prospeccao')),
            ],
            options={
                'ordering': ['data_registro'],
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('status', models.CharField(choices=[('NAO_INICIADA', 'Não Iniciada'), ('INICIADA', 'Iniciada'), ('FINALIZADA', 'Finalizada')], default='NAO_INICIADA', max_length=20)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('data_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Data de Início')),
                ('data_finalizacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Finalização')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarefas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('finalizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tarefas_finalizadas', to=settings.AUTH_USER_MODEL, verbose_name='Finalizado por')),
                ('iniciado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tarefas_iniciadas', to=settings.AUTH_USER_MODEL, verbose_name='Iniciado por')),
            ],
        ),
        migrations.CreateModel(
            name='AcaoTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição da Ação')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='uploads/tarefas/%Y/%m/', verbose_name='Arquivo Anexo')),
                ('data_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Registro')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes', to='app.tarefa', verbose_name='Tarefa')),
            ],
            options={
                'ordering': ['data_registro'],
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_servico', models.DateField(verbose_name='Data do Serviço')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade de Viagens')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Registro')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicos', to='app.cliente', verbose_name='Cliente')),
                ('fechado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicos_fechados', to=settings.AUTH_USER_MODEL, verbose_name='Fechado Por')),
                ('tipo_servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.tiposervico', verbose_name='Tipo de Serviço')),
            ],
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField(verbose_name='Mês Base')),
                ('ano', models.PositiveIntegerField(verbose_name='Ano Base')),
                ('dias_uteis', models.PositiveIntegerField(default=20, verbose_name='Dias Úteis')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Meta a ser alcançada (R$)')),
                ('representante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to=settings.AUTH_USER_MODEL, verbose_name='Representante')),
            ],
            options={
                'ordering': ['-ano', '-mes', 'representante'],
                'unique_together': {('representante', 'mes', 'ano')},
            },
        ),
    ]
