# Generated by Django 5.2.7 on 2026-01-14 18:11


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospeccao',
            name='numero_controle',
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name='Numero de Controle'
            ),
        ),
    ]
