# Generated by Django 5.2.7 on 2026-01-14 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteprospect',
            name='promovido',
            field=models.BooleanField(default=False, verbose_name='Foi Promovido a Cliente'),
        ),
        migrations.AddField(
            model_name='clienteprospect',
            name='data_promocao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Promocao'),
        ),
        migrations.AddField(
            model_name='clienteprospect',
            name='cliente_ativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospect_origem', to='app.cliente', verbose_name='Cliente Ativo Relacionado'),
        ),
        migrations.AddField(
            model_name='prospeccao',
            name='numero_controle',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Numero de Controle'),
        ),
    ]