# Generated by Django 5.2.7 on 2025-12-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_cliente_filial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='setor',
            field=models.CharField(choices=[('REPRESENTANTE', 'Representante Comercial'), ('COMERCIAL', 'Diretoria Comercial'), ('ADMIN', 'Administrativo (TI/Sistema)')], default='REPRESENTANTE', max_length=20, verbose_name='Setor / Função'),
        ),
    ]
