# Generated by Django 5.2.7 on 2026-02-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_add_numero_controle'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospeccao',
            name='tipo_proposta',
            field=models.CharField(choices=[('COMEX', 'COMEX/DOMESTIC'), ('PROJETO', 'PROJETO')], default='COMEX', max_length=20, verbose_name='Tipo de Proposta'),
        ),
    ]
