# Generated by Django 5.2.7 on 2026-02-04 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_prospeccao_tipo_proposta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='atribuido_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tarefas_atribuidas', to=settings.AUTH_USER_MODEL, verbose_name='Atribuído a'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='data_agendamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data Agendamento'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='visualizada_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Visualizada em'),
        ),
    ]
