# Generated by Django 5.2.7 on 2026-01-03 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_profile_setor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospeccao',
            name='tipo_proposta',
        ),
        migrations.AddField(
            model_name='prospeccao',
            name='tipo_servico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.tiposervico', verbose_name='Tipo de Serviço'),
        ),
    ]
