# Generated by Django 5.2.7 on 2026-02-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_tarefa_atribuido_a_tarefa_data_agendamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('NAO_INICIADA', 'Pendente'), ('INICIADA', 'Iniciada'), ('FINALIZADA', 'Finalizada'), ('REALIZADA', 'Realizada'), ('NAO_REALIZADA', 'Não Realizada')], default='NAO_INICIADA', max_length=20),
        ),
    ]
