# Generated by Django 5.2.7 on 2026-02-04 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_tarefa_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TarefaAgendada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('data_agendamento', models.DateField(verbose_name='Data Agendamento')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('REALIZADA', 'Realizada'), ('NAO_REALIZADA', 'Não Realizada')], default='PENDENTE', max_length=20)),
                ('visualizada_em', models.DateTimeField(blank=True, null=True, verbose_name='Visualizada em')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_finalizacao', models.DateTimeField(blank=True, null=True)),
                ('atribuido_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas_agendadas_atribuidas', to=settings.AUTH_USER_MODEL, verbose_name='Atribuído a')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas_agendadas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('finalizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_agendadas_finalizadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
