# Generated by Django 5.2.7 on 2026-04-07 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_feriado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prospeccao',
            name='atribuido_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prospeccoes_atribuidas', to=settings.AUTH_USER_MODEL, verbose_name='Atribuído a'),
        ),
    ]
