# Generated by Django 5.2.7 on 2026-05-07 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
        ('app', '0008_prospeccao_atribuido_a'),
    ]

    operations = [
    ]
